# Codecov configuration for NOAA-GFDL/fre-cli
# Reference: https://docs.codecov.com/docs/codecovyml-reference

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        if_ci_failed: error

    patch:
      default:
        target: 50%          # Minimum coverage for new code
        threshold: 1%        # Allow 1% decrease
        if_ci_failed: error

comment:
  layout: "header, diff, flags, components, files, footer"
  behavior: default
  require_changes: false
