# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details
# Required
version: 2

# environment
conda:
  environment: environment.yml

# install
# Optionally, but recommended,
# declare the Python requirements required to build your documentation
# See https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs

sphinx:
  configuration: docs/conf.py


# # build
# See https://docs.readthedocs.com/platform/stable/builds.html
# See https://docs.readthedocs.com/platform/stable/build-customization.html
# Set the OS, Python version, and other tools you might need
build:
  os: ubuntu-24.04
  tools:
    python: "mambaforge-latest"
  jobs:
    pre_create_environment:
      - conda update --yes --quiet --name=base --channel=conda-forge conda
    pre_build:
      - sphinx-apidoc --ext-autodoc --output-dir docs fre/ --separate



