{% set data = load_setup_py_data() %}

package:
  name: fre-cli
  version: '{{ environ.get("GIT_DESCRIBE_TAG", data.get("version")) }}'

# conda-build will always defer to what's specified here
source:
  path: .
#  git_url: https://github.com/NOAA-GFDL/fre-cli.git

build:
  script:
    - {{ PYTHON }} -m pip install . -vv
    - cp fre/mkmf/bin/mkmf $PREFIX/bin
    - cp fre/mkmf/bin/list_paths $PREFIX/bin
    - cp fre/mkmf/bin/git-version-string $PREFIX/bin
  number: 1
  noarch: python

channels:
    - conda-forge
    - noaa-gfdl

requirements:
  host:
    - python=3.11.*
    - pip
  run:
    - python=3.11.*
    - pip
    - noaa-gfdl::analysis_scripts
    - noaa-gfdl::catalogbuilder>=2.0.2
    - noaa-gfdl::fre-nctools
    - conda-forge::cftime
    - conda-forge::click>=8.2
    - conda-forge::cylc-flow>=8.2.0
    - conda-forge::cylc-rose
    - conda-forge::cmor>=3.11.0
    - conda-forge::cdo>=2.0.0
    - conda-forge::jinja2=3.0.*
    - conda-forge::jsonschema
    - conda-forge::metomi-rose
    - conda-forge::nccmp
    - conda-forge::numpy<2
    - conda-forge::pylint
    - conda-forge::pytest
    - conda-forge::pytest-cov
    - conda-forge::python-cdo
    - conda-forge::pyyaml
    - conda-forge::xarray

test:
  source_files:
    - fre/
  files:
    - fre/mkmf/templates/*
  imports:
    - fre
    - fre.app
    - fre.catalog
    - fre.check
    - fre.cmor
    - fre.list_
    - fre.make
    - fre.pp
    - fre.run
    - fre.yamltools
  commands:
    - pylint --fail-under 9.00 --max-line-length 120 --max-args 6 -ry --ignored-modules netCDF4,cmor fre/
    # run pytest but ignore any tests that require compilation
    - pytest --durations=20 --log-level INFO --ignore=fre/make/tests/compilation fre/ 
    - fre --help
    - fre app --help
    - fre catalog --help
    - fre check --help
    - fre cmor --help
    - fre list --help
    - fre make --help
    - fre pp --help
    - fre run --help
    - fre yamltools --help


about:
  home: https://github.com/NOAA-GFDL/fre-cli
  license: Apache2.0
  license_file: LICENSE.md
  summary: Command line interface for FMS Runtime Environment (FRE) workflow commands
  author: Bennett Chang, Dana Singh, Chris Blanton
