package:
  name: fre-cli
  version: 0.1.0

source:
  # url: https://github.com/NOAA-GFDL/fre-cli
  path: .

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - python
    - pip
  run:
    - python
    - click
    - pyyaml
    - jsonschema

test:
  imports:
    - click
    - fre

about:
  # home: https://github.com/NOAA-GFDL/fre-cli
  license: LGPL-3.0
  license_file: LICENSE.md
  summary: Command line interface for FMS Runtime Environment (FRE) workflow commands
  author: Bennett Chang, Dana Singh, Chris Blanton

# extra:
#   files:
#   - /fre/frepp/schema.json