{% set data = load_setup_py_data() %}

package:
  name: fre-cli
  version: '{{ environ.get("GIT_DESCRIBE_TAG", data.get("version")) }}'

# conda-build will always defer to what's specified here
source:
  path: .
#  git_url: https://github.com/NOAA-GFDL/fre-cli.git

build:
  script:
    - {{ PYTHON }} -m pip install . -vv
  number: 1
  noarch: python

channels:
    - conda-forge
    - noaa-gfdl

requirements:
  host:
    - python==3.10
    - pip
  run:
    - python==3.10
    - pip
    - click
    - pyyaml
    - pylint
    - jsonschema
    - noaa-gfdl::catalogbuilder
    - noaa-gfdl::fre-nctools
    - noaa-gfdl::analysis_scripts
    - conda-forge::nccmp
    - conda-forge::cylc-flow>=8.2.0
    - conda-forge::cylc-rose
    - conda-forge::metomi-rose
    - conda-forge::cmor>=3.9.0
    - conda-forge::pytest
    - conda-forge::pytest-cov
    - conda-forge::python-cdo
    - conda-forge::cdo>=2.0.0

test:
  requires:
    - pip
    - pylint
    - pytest
    - pytest-cov
  source_files:
    - fre/
  files:
    - mkmf/templates/linux-ubuntu-xenial-gnu.mk
  imports:
    - fre
    - fre.app
    - fre.catalog
    - fre.check
    - fre.cmor
    - fre.list_
    - fre.make
    - fre.pp
    - fre.run
    - fre.yamltools
  commands:
    - pylint --max-line-length 120 --max-args 6 -ry --ignored-modules netCDF4,cmor fre/ || echo "pylint returned non-zero exit code and will kill the workflow. guarding against this now."
    # run pytest but ignore any tests that require compilation
    - coverage run -m pytest --ignore=fre/make/tests/compilation --config-file=fre/pytest.ini --cov-report term-missing --cov-config=fre/coveragerc --cov=fre fre/ 
    - fre --help
    - fre app --help
    - fre catalog --help
    - fre check --help
    - fre cmor --help
    - fre list --help
    - fre make --help
    - fre pp --help
    - fre run --help
    - fre yamltools --help


about:
  home: https://github.com/NOAA-GFDL/fre-cli
  license: LGPL-3.0
  license_file: LICENSE.md
  summary: Command line interface for FMS Runtime Environment (FRE) workflow commands
  author: Bennett Chang, Dana Singh, Chris Blanton
