{% set data = load_setup_py_data() %}

package:
  name: fre-cli
  version: '{{ environ.get("GIT_DESCRIBE_TAG", data.get("version")) }}'

source:
  path: .

build:
  script:
    - {{ PYTHON }} -m pip install . -vv
    - cp fre/mkmf/bin/mkmf $PREFIX/bin
    - cp fre/mkmf/bin/list_paths $PREFIX/bin
    - cp fre/mkmf/bin/git-version-string $PREFIX/bin
  number: 1
  noarch: python

channels:
    - conda-forge
    - noaa-gfdl

requirements:
  host:
    - conda-forge::python=3.11.*
  run:
    - noaa-gfdl::analysis_scripts
    - noaa-gfdl::catalogbuilder>=2.0.2
    - noaa-gfdl::fre-nctools
    - conda-forge::cdo>=2
    - conda-forge::cftime>=1.6.*
    - conda-forge::click>=8.2
    - conda-forge::cmor=3.11.*
    - conda-forge::cylc-flow>=8.2
    - conda-forge::cylc-rose
    - conda-forge::jinja2>=3
    - conda-forge::jsonschema
    - conda-forge::metomi-rose
    - conda-forge::nccmp
    - conda-forge::netcdf4
    - conda-forge::numpy=1.26.*
    - conda-forge::python=3.11.*
    - conda-forge::python-cdo
    - conda-forge::pyyaml
    - conda-forge::xarray
    
test:
  requires:
    - conda-forge::pytest
    - conda-forge::pytest-cov
    - conda-forge::pylint
  source_files:
    - fre/
  files:
    - fre/mkmf/templates/*
  imports:
    - fre
    - fre.app
    - fre.catalog
    - fre.check
    - fre.cmor
    - fre.list_
    - fre.make
    - fre.pp
    - fre.run
    - fre.yamltools
  commands:
    - fre --help
    - fre app --help
    - fre catalog --help
    - fre check --help
    - fre cmor --help
    - fre list --help
    - fre make --help
    - fre pp --help
    - fre run --help
    - fre yamltools --help
    - pylint --fail-under 7.30 --max-line-length 120 --max-args 6 -ry --ignored-modules netCDF4,cmor fre/
    - pytest --durations=20 --log-level INFO --ignore=fre/make/tests/compilation fre/ 


about:
  home: https://github.com/NOAA-GFDL/fre-cli
  license: Apache2.0
  license_file: LICENSE.md
  summary: Command line interface for FMS Runtime Environment (FRE) workflow commands
  author: Bennett Chang, Dana Singh, Chris Blanton
