{% set data = load_setup_py_data() %}

package:
  name: fre-cli
  version: '{{ environ.get("GIT_DESCRIBE_TAG", data.get("version")) }}'

source:
  path: .
# ideally we want this git_url path, but it messes with conda publish
# where it builds only the sourced url and not local/branch changes
# git_url: https://github.com/NOAA-GFDL/fre-cli

build:
  script: 
    - {{ PYTHON }} -m pip install . -vv
  number: 1
  noarch: python

channels:
    - defaults
    - conda-forge
    - noaa-gfdl

requirements:
  host:
    - python
    - pip
  run:
    - python
    - click
    - pyyaml
    - pylint
    - jsonschema
    - noaa-gfdl::intakebuilder
    - conda-forge::cylc-flow>=8.2.0
    - conda-forge::cylc-rose
    - conda-forge::metomi-rose
    - conda-forge::cmor
    - conda-forge::cylc-uiserver
    - conda-forge::pytest
    - conda-forge::pytest-cov
    - conda-forge::python-cdo
    - conda-forge::cdo>=2.0.0

test:
  source_files: 
    - fre/
  imports:
    - click
    - pytest
    - pylint
    - fre
    - fre.pp
    - fre.pp.install
    - fre.pp.status
    - fre.pp.run
    - fre.pp.validate
    - fre.make
    - fre.app
    - fre.cmor
  commands:
    - pytest --config-file=fre/pytest.ini --cov-config=fre/coveragerc --cov=fre fre/
    - pylint fre/ || echo "pylint returned non-zero exit code and will kill the workflow. guarding against this now."
    - fre --help
    - fre pp --help
    - fre pp install --help
    - fre pp status --help
    - fre pp run --help
    - fre pp validate --help
    - fre make --help
    - fre make create-checkout --help
    - fre make create-compile --help
    - fre make create-dockerfile --help
    - fre make create-makefile --help
    - fre make run-fremake --help
    - fre app --help
    - fre app mask-atmos-plevel --help
    - fre cmor --help
    - fre cmor run --help

  requires:
    - pip
    - pylint
    - pytest
    - pytest-cov

about:
  home: https://github.com/NOAA-GFDL/fre-cli
  license: LGPL-3.0
  license_file: LICENSE.md
  summary: Command line interface for FMS Runtime Environment (FRE) workflow commands
  author: Bennett Chang, Dana Singh, Chris Blanton
