"""
Create_compile_script consists of one method called compile_create to  
retrieve information from the resolved YAML configuration to generate a compile.sh
script to

    [modelRoot]/[experiment]/[platform]-[target]/exec/compile.sh

where

- `modelRoot` is defined in platforms.yaml
- `experiment` is the experiment value in compile.yaml
- `platform` and `target` are passed via the -p / -t CLI options 
  to `fre make compile-script` and `fre make all`

When executed, compile.sh

    1. Sets src_dir (where source code was checked out by checkout.sh)
    2. Sets bld_dir (the exec/ directory where the executable is placed)
    3. Sets the path to the mkmf template (value to mkTemplate key in platforms.yaml)
    4. Loads the correct environment modules to set the compile environment
       (see envSetup in platforms.yaml)
    5. Calls mkmf for each model component listed under src in compile.yaml
       to generate component Makefiles
    6. Calls make (with -j [makejobs]) to build the model executable

Container platforms are silently skipped — compilation inside a container image
is handled by the Dockerfile generated by `fre make dockerfile`.
"""

import logging
from multiprocessing.dummy import Pool
from pathlib import Path
from typing import Optional

import fre.yamltools.combine_yamls_script as cy
from fre.make.make_helpers import get_mktemplate_path

from .gfdlfremake import (
    buildBaremetal,
    targetfre,
    varsfre,
    yamlfre
)


fre_logger = logging.getLogger(__name__)

def compile_create(yamlfile:str, platform:tuple[str], target:tuple[str], makejobs: int = 4,
                   nparallel: int = 1, execute: Optional[bool] = False,
                   verbose: Optional[bool] = None):
    """
    Generates the compile.sh script for each bare-metal platform and target combination, and
    optionally executes compile.sh to compile a model executable.

    For each bare-metal platform-target combination, a compile.sh script is written to
    [modelRoot]/[experiment]/[platform]-[target]/exec/.  

    :param yamlfile: is the path to the model YAML file (e.g. am5.yaml). 
    :type yamlfile: str
    :param platform: is one or more FRE platform strings as defined in the platform yaml
                     (e.g. ncrc5.intel23).  Container platforms in this tuple are
                     silently ignored.
    :type platform: tuple[str]
    :param target: is one or more mkmf target strings (e.g. debug-openmp, repro-openmp, prod-openmp)
                   One compile.sh is generated per platform/target pair.
    :type target: tuple[str]
    :param makejobs: is the number of Makefile recipes to run simultaneously, passed to
                     make -j.  Defaults to 4.
    :type makejobs: int
    :param nparallel: is the number of compile.sh scripts to run concurrently when
                      execute=True.  Defaults to 1.
    :type nparallel: int
    :param execute: is a flag where if True, run every generated compile.sh after creation.
                    Defaults to False.
    :type execute: bool
    :param verbose: is a flag where if True, set logger level to "DEBUG" for detailed output.
                    Defaults to False, setting the logger level set to "INFO".
    :type verbose: bool

    :raises ValueError:
        - If a specified platform does not exist in the platforms yaml.
        - If the mkTemplate path defined in the platforms yaml does not exist.
    """

    # Define variables
    yml = yamlfile
    name = yamlfile.split(".")[0]
    jobs = str(makejobs)

    if verbose:
        fre_logger.setLevel(level=logging.DEBUG)
    else:
        fre_logger.setLevel(level=logging.INFO)

    baremetal_run = False  # This is needed if there are no bare metal runs

    ## Split and store the platforms and targets in a list
    plist = platform
    tlist = target

    # Combine model, compile, and platform yamls
    full_combined = cy.consolidate_yamls(yamlfile=yml,
                                         experiment=name,
                                         platform=platform,
                                         target=target,
                                         use="compile",
                                         output=None)

    ## Get the variables in the model yaml
    fre_vars = varsfre.frevars(full_combined)

    ## Open the yaml file, validate the yaml, and parse as fremake_yaml
    model_yaml = yamlfre.freyaml(full_combined, fre_vars)
    fremake_yaml = model_yaml.getCompileYaml()

    ## Error checking the targets
    for target_name in tlist:
        target = targetfre.fretarget(target_name)

    fremake_build_list = []
    ## Loop through platforms and targets
    for platform_name in plist:
        for target_name in tlist:
            target = targetfre.fretarget(target_name)
            if not model_yaml.platforms.hasPlatform(platform_name):
                raise ValueError(f"{platform_name} does not exist in platforms.yaml")

            platform = model_yaml.platforms.getPlatformFromName(platform_name)
            ## Make the bld_dir based on the modelRoot, the platform, and the target
            src_dir = platform["modelRoot"] + "/" + fremake_yaml["experiment"] + "/src"
            ## Check for type of build
            if platform["container"] is False:
                baremetal_run = True
                bld_dir = f'{platform["modelRoot"]}/{fremake_yaml["experiment"]}/' + \
                         f'{platform_name}-{target.gettargetName()}/exec'
                Path(bld_dir).mkdir(parents = True, exist_ok = True)

                template_path = get_mktemplate_path(mk_template = platform["mkTemplate"],
                                                    model_root = platform["modelRoot"],
                                                    container_flag = platform["container"])

                ## Create a list of compile scripts to run in parallel
                fremake_build = buildBaremetal.buildBaremetal(exp=fremake_yaml["experiment"],
                                                             mkTemplatePath=template_path,
                                                             srcDir=src_dir,
                                                             bldDir=bld_dir,
                                                             target=target,
                                                             env_setup=platform["envSetup"],
                                                             jobs=jobs)
                for c in fremake_yaml['src']:
                    fremake_build.writeBuildComponents(c)
                fremake_build.writeScript()
                fremake_build_list.append(fremake_build)
                fre_logger.info("Compile script created here: %s/compile.sh", bld_dir)

    if execute:
        if baremetal_run:
            pool = Pool(processes=nparallel)  # Create a multiprocessing Pool
            pool.map(buildBaremetal.fremake_parallel, fremake_build_list)  # process data_inputs iterable with pool
