#TRACK IMAGES: https://hub.docker.com/_/ubuntu
FROM ubuntu:26.04 as builder

# Install micromamba: micromamba is a tinier and faster version of mamba
# Set where the micromamba env creation goes
ARG micromamba_env_location=/app/cylc-flow-tools

## needed for micromamba installation: curl, bzip2, ca-certificate (used to securely connect to pkg repos over HTTPS)
## needed for stage-history pp task: uuid-runtime, time
## needed for refine-diag pp task: csh
RUN apt-get update && apt-get install -y \
  curl \
  bzip2 \
  ca-certificates \
  uuid-runtime \
  time \
  csh

RUN curl -Ls https://micro.mamba.pm/api/micromamba/linux-64/latest | tar -xvj bin/micromamba

# Copy runscript in container and make it executable
COPY /container-files/runscript.sh /app/exec/runscript.sh
RUN chmod +x /app/exec/runscript.sh

## Set up conda environment directory for cylc workflow
COPY container-files/cylc-flow-tools.yaml ${micromamba_env_location}/cylc-flow-tools.yaml

RUN micromamba env create --file ${micromamba_env_location}/cylc-flow-tools.yaml -p ${micromamba_env_location}/env \
  && micromamba clean --all --yes

# Keeping in comment for now - might be useful for cylc workflow-state or tui things
#RUN micromamba install urwid==2.*

# Put env in path so it is already activated upon runtime
ENV PATH=${micromamba_env_location}/env/bin:$PATH

ENTRYPOINT ["/bin/bash"]
