name: pytest

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  pull_request:
    branches:
  push:
    branches:
      - main
  schedule:
    # Runs at 00:00 UTC every day (testing with 17:00 UTC == 1 PM eastern)
    - cron: '10 17 * * *'

# cancel running jobs if theres a newer push
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  condaenvcreate:
    name: Test Python TESTING ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.12', '3.13', '3.14']
    container:
      image: ghcr.io/noaa-gfdl/fre-cli:production
      options: "--privileged --device=/dev/fuse --security-opt label=disable"
      #options: "--privileged --cap-add=sys_admin --cap-add=mknod --device=/dev/fuse --security-opt seccomp=unconfined --security-opt label=disable --security-opt apparmor=unconfined" # needed for podman
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Activate fre-cli Environment and install different python versions to test
        run: |
          source /opt/conda/etc/profile.d/conda.sh
          conda deactivate
          conda activate /app/cylc-flow-tools

          #install specfic python version
          conda install -y -p /app/cylc-flow-tools "python=${{ matrix.python-version }}"

          # Add environment path to GITHUB_PATH so changes persist across job steps
          # Ensures the environment will already be activated across steps
          echo "/app/cylc-flow-tools/bin" >> $GITHUB_PATH

      - name: Install pytest-cov and c++ compiler
        run: |
          #pytest-cov needed for testing
          #c++ compiler needed for cartopy for analysis script installation tests
          conda install -y -p /app/cylc-flow-tools -c conda-forge pytest-cov cxx-compiler

      - name: Install the fre-cli
        run: |
          #install fre
          python -m pip install .

      - name: Verify Python/fre-cli/pytest-cov Installation
        run: |
          echo "Python version installed: "
          conda list -p /app/cylc-flow-tools

      - name: Run pytest in fre-cli env (tests that don't need podman)
        run: |
          echo "adding spack installed binaries of netcdf/hdf5 to front of path, so conda installed ones don't break compilation tests"
          export PATH="/opt/views/view/bin:$PATH"
          echo "PATH is $PATH"

          echo "running pytest, will print 20 longest durations"
          python -m pytest --durations=20 --log-level DEBUG --cov-report=xml --cov-config=coveragerc --cov=fre fre/ --ignore fre/make/tests/compilation

      - name: Install podman and apptainer
        run: |
          ##podman and apptainer needed to run fre make compilation tests
          #conda install -y -p /app/cylc-flow-tools -c conda-forge podman apptainer

          ###INSTALL BINARIES NEEDED FOR PODMAN RUNNING
          ##create signature verification policy file/podman runtime files
          ##this permits podman to use any image from the local storage transport on the runner
          ##limited to runner's local container store; only applies to current pipeline execution
          ##because runners are ephemeral.....
          ##TO-DO: CHECK IF THIS IS OK
          #mkdir -p /etc/containers
          #if [ ! -f /etc/containers/policy.json ]; then
          #    cat > /etc/containers/policy.json <<'EOF'
          #{
          # "default": [{"type": "reject"}],
          # "transports": {
          #     "docker": {
          #         "ghcr.io/rem1776/hpc-mini:alpine3gcc14.2":[{"type":"insecureAcceptAnything"}]
          #     },
          #     "containers-storage": {
          #         "": [{"type": "insecureAcceptAnything"}]
          #     }
          # }
          #}
          #EOF
          #fi

          ## registries config
          #cat > /etc/containers/registries.conf <<'EOF'
          #[registries.search]
          #registries = ['docker.io']
          #EOF

          ## variables that might be needed
          #export PODMAN_STORAGE_DRIVER=vfs
          #export XDG_RUNTIME_DIR=/tmp/run/users/$(id -u)
          #mkdir -p $XDG_RUNTIME_DIR

          #configure networking
          apt-get update
          apt-get install -y software-properties-common
          add-apt-repository -y universe
          apt-get install -y \
            fuse-overlaysfs \
            podman \
            apptainer \
            nftables \ 
            && rm -rf /var/lib/apt/lists/*
 
      - name:  Run pytest in fre-cli env (tests that need podman and apptainer)
        run: |
          echo "adding spack installed binaries of netcdf/hdf5 to front of path, so conda installed ones don't break compilation tests"
          export PATH="/opt/views/view/bin:$PATH"
          echo "PATH is $PATH"

          echo "running pytest, will print 20 longest durations"
          python -m pytest --durations=20 --log-level DEBUG --cov-report=xml --cov-config=coveragerc --cov-append --cov=fre fre/make/tests/compilation

      - name: Install gpg for Codecov upload
        run: | 
          apt-get update
          apt-get install -y gnupg

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v5
        with:
          verbose: true
          files: coverage.xml
          flags: unittests
          token: ${{ secrets.CODECOV_TOKEN }}
