name: create_test_conda_env_container

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  pull_request:
    branches:
  push:
    branches:
      - main
  schedule:
    # Runs at 00:00 UTC every day (testing with 17:00 UTC == 1 PM eastern)
    - cron: '10 17 * * *'

# cancel running jobs if theres a newer push
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  condaenvcreate:
    name: Test Python TESTING ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.12', '3.13', '3.14']
    container:
      image: ghcr.io/noaa-gfdl/fre-cli:production
    defaults:
      run:
        shell: bash -l {0}

      #options: "--privileged --cap-add=sys_admin --cap-add=mknod --device=/dev/fuse --security-opt seccomp=unconfined --security-opt label=disable --security-opt apparmor=unconfined" # needed for podman
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Activate fre-cli Environment and Install fre-cli
        run: |
          source /opt/conda/etc/profile.d/conda.sh
          conda deactivate
          conda activate /app/cylc-flow-tools

          #install specfic python version
          conda install -y -p /app/cylc-flow-tools "python=${{ matrix.python-version }}"
          conda install -y -p /app/cylc-flow-tools -c conda-forge pytest-cov cxx-compiler #c++ compiler needed for cartopy for analysis script installation tests
          #install fre
          python -m pip install .

          # Add environment path to GITHUB_PATH so changes persist across job steps
          # Ensures the environment will already be activated across steps
          echo "/app/cylc-flow-tools/bin" >> $GITHUB_PATH

      - name: Verify Python/fre-cli/pytest-cov Installation
        run: |
          echo "Python version installed: "
          conda list -p /app/cylc-flow-tools

      - name: Run pytest In fre-cli Env
        run: |
          #echo "to run conda init, sourcing /some/path/to/conda/etc/profile.d/conda.sh"
          #source /opt/software/linux-rocky9-zen2/gcc-11.4.1/miniconda3-24.7.1-akg5caxhoqv3oasili3pgukbyryceq74/etc/profile.d/conda.sh

          #echo "to activate env, conda init"
          #conda init

          #echo "activating the fre-cli environment"
          #conda activate fre-cli

          echo "adding spack installed binaries of netcdf/hdf5 to front of path, so conda installed ones don't break compilation tests"
          export PATH="/opt/views/view/bin:$PATH"
          echo "PATH is $PATH"

          echo "running pytest, will print 20 longest durations"
          python -m pytest --durations=20 --log-level DEBUG --cov-report=xml --cov-config=coveragerc --cov=fre fre/

      - name: Install gpg for Codecov upload
        run: | 
          apt-get update
          apt-get install -y gnupg

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v5
        with:
          verbose: true
          files: coverage.xml
          flags: unittests
          token: ${{ secrets.CODECOV_TOKEN }}
