name: Build and Push Container Image

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: "noaa-gfdl/fre-cli"
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["publish_conda"]
    types: [completed]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch all tags
        run: git fetch --tags

      - name: Determine latest tag
        id: set_tag
        run: |
          echo "docker_tag=$(git describe --tags --abbrev=0)" >> "$GITHUB_OUTPUT"

      - name: Show image tag
        run: echo "Docker tag is ${{ steps.set_tag.outputs.docker_tag }}"

      - name: Update fre-cli version in cylc-flow-tools.yaml
        run: |
          sed -i 's/^[[:space:]]*-[[:space:]]*noaa-gfdl::fre-cli==.*/  - noaa-gfdl::fre-cli==${{ steps.set_tag.outputs.docker_tag }}/' ./container-files/cylc-flow-tools.yaml

      - name: Log in to the Container registry
        if: ${{ github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success' }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        if: ${{ github.event_name == 'workflow_dispatch' || (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') }}
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./container-files/Dockerfile-fre-cli
          push: ${{ github.event_name == 'workflow_run' }}
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.set_tag.outputs.docker_tag }}
