name: Build and Push Container Image

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: "Skip pushing container image"
        required: true
        default: "true"
        type: choice
        options: ["true", "false"]

  repository_dispatch:
    types: [publish-conda-succeeded]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: "noaa-gfdl/ubuntu-20-frecli-2025"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine image tag
        id: set_tag
        run: |
          # Use the pushed tag if this is a tag ref; otherwise fall back.
          if [[ "$GITHUB_REF" == refs/tags/* ]]; then
            TAG="${GITHUB_REF#refs/tags/}"
          elif [[ "${GITHUB_REF_NAME}" == "main" ]]; then
            TAG="latest"
          else
            TAG="${GITHUB_SHA::7}"
          fi
          echo "docker_tag=$TAG" >> "$GITHUB_OUTPUT"

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        if: ${{ inputs.dry_run != 'true' }}
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./container-files/Dockerfile-frecli
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.set_tag.outputs.docker_tag }}
